# Generated by Django 3.1.3 on 2020-12-01 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('question_text', models.CharField(max_length=200)),
                ('cant_pc', models.IntegerField(default=1, max_length=50)),
                ('disponibilidad', models.BooleanField(default='true')),
            ],
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('mp3', 'Audio'), ('doc', 'Documento'), ('mp3', 'Eliminado'), ('img', 'Imagenes'), ('sfw', 'Software')], max_length=3)),
                ('autor', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('inventario', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('d', 'Disponible'), ('o', 'Ocupada'), ('r', 'Rota')], max_length=1)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionLab.laboratorio')),
            ],
        ),
    ]
