# Generated by Django 3.2.9 on 2021-12-25 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id_laboratorio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=50)),
                ('cant_pc', models.IntegerField(default=1)),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='Disponibilidad')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(
                    choices=[('mp3', 'Audio'), ('doc', 'Documento'), ('img', 'Imagenes'), ('mov', 'Video')],
                    help_text='Seleccione el tipo de material', max_length=3)),
                ('autor', models.CharField(max_length=100)),
                ('descripcion', models.TextField(help_text='Ingrese una breve descripción del material')),
                ('url', models.URLField()),
                ('idioma', models.CharField(default='Ingles', max_length=100)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id_maquina', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('num_inv', models.CharField(max_length=20, verbose_name='Inventario')),
                ('estado', models.CharField(choices=[('d', 'Disponible'), ('o', 'Ocupada'), ('r', 'Rota')], default='d',
                                            max_length=1)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionLab.laboratorio')),
            ],
            options={
                'verbose_name': 'Maquina',
                'verbose_name_plural': 'Maquinas',
            },
        ),
    ]
