# Generated by Django 3.2.9 on 2021-12-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='id_laboratorio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='id_maquina',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='id_material',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
