# Generated by Django 3.1.3 on 2020-12-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLab', '0003_auto_20201201_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquina',
            old_name='inventario',
            new_name='num_inv',
        ),
    ]
