# Generated by Django 3.1.3 on 2020-12-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLab', '0004_auto_20201201_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='disponibilidad',
            field=models.BooleanField(default=True, verbose_name='Disponibilidad'),
        ),
    ]
