# Generated by Django 3.1.3 on 2020-12-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLab', '0006_auto_20201201_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratorio',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='maquina',
            options={'verbose_name': 'Maquina', 'verbose_name_plural': 'Maquinas'},
        ),
        migrations.AlterField(
            model_name='maquina',
            name='estado',
            field=models.CharField(choices=[('d', 'Disponible'), ('o', 'Ocupada'), ('r', 'Rota')], default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='descripcion',
            field=models.TextField(help_text='Ingrese una breve descripción del material'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='tipo',
            field=models.CharField(choices=[('mp3', 'Audio'), ('doc', 'Documento'), ('img', 'Imagenes'), ('mov', 'Video')], help_text='Seleccione el tipo de material', max_length=3),
        ),
    ]
