# Generated by Django 3.1.3 on 2020-12-01 19:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('fechaCreada', models.DateTimeField(default=datetime.datetime(2020, 12, 1, 19, 25, 8, 812880, tzinfo=utc), verbose_name='Fecha Creada')),
                ('estado', models.CharField(choices=[('borrador', 'En borrador'), ('publico', 'Publicado'), ('delete', 'Eliminado')], max_length=8)),
                ('body', tinymce.models.HTMLField()),
            ],
        ),
    ]
