# Generated by Django 3.2.9 on 2021-12-25 20:58

import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id_convocatoria', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado',
                 models.CharField(choices=[('B', 'En borrador'), ('P', 'Publicado'), ('D', 'Eliminado')], default='B',
                                  max_length=1, verbose_name='Estado')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('fechaCreada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creada')),
                ('body', tinymce.models.HTMLField(null=True, verbose_name='Contenido')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha',
                 models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de la Inscripción')),
                ('lugar', models.CharField(max_length=100, verbose_name='Lugar de la Inscripción')),
                ('disponibilidad', models.IntegerField(help_text='Cantidad de usuarios que se pueden inscribir')),
                ('convocatoria',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Convocatorias.convocatoria')),
                ('estudiantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
    ]
