# Generated by Django 3.2.9 on 2021-12-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='id_convocatoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
