# Generated by Django 3.1.3 on 2020-12-01 19:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='fechaCreada',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 19, 25, 26, 534171, tzinfo=utc), verbose_name='Fecha Creada'),
        ),
    ]
