# Generated by Django 3.2.9 on 2021-12-28 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Convocatorias', '0002_alter_convocatoria_id_convocatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='id_convocatoria',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='id_inscripcion',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
