# Generated by Django 3.1.3 on 2020-12-01 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Convocatorias', '0002_auto_20201201_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='fechaCreada',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 19, 30, 48, 958666, tzinfo=utc), verbose_name='Fecha Creada'),
        ),
    ]
