# Generated by Django 3.2.9 on 2022-01-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convocatorias', '0003_auto_20211228_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='img',
            field=models.ImageField(default='null', upload_to='static\\media'),
        ),
    ]
