# Generated by Django 3.2.9 on 2022-01-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Convocatorias', '0004_convocatoria_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='id_convocatoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
