# Generated by Django 3.1.3 on 2020-12-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convocatorias', '0005_remove_convocatoria_fechacreada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
