# Generated by Django 3.1.3 on 2020-12-01 21:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Convocatorias', '0006_auto_20201201_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='fechaCreada',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 21, 14, 40, 57072, tzinfo=utc), verbose_name='Fecha creada'),
        ),
    ]
