# Generated by Django 3.1.3 on 2020-12-04 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Convocatorias', '0008_auto_20201201_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='fechaCreada',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creada'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
    ]
