# Generated by Django 3.1.3 on 2030-12-12 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Convocatorias', '0010_auto_20201209_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='estado',
            field=models.CharField(choices=[('B', 'En borrador'), ('P', 'Publicado'), ('D', 'Eliminado')], default='B', max_length=1),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de la Inscripción')),
                ('lugar', models.CharField(max_length=100, verbose_name='Lugar de la inscripcio')),
                ('disponibilidad', models.IntegerField(help_text='Cantidad de usuarios que se pueden inscribir')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Convocatorias.convocatoria')),
                ('estudiantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
