# Generated by Django 3.1.3 on 2030-12-12 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Convocatorias', '0011_auto_20301212_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='autor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
