# Generated by Django 3.2.9 on 2021-12-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convocatorias', '0013_auto_20301212_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='lugar',
            field=models.CharField(max_length=100, verbose_name='Lugar de la Inscripción'),
        ),
    ]
