# Generated by Django 3.2.9 on 2021-12-25 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GestionLab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reservacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('laboratorio',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionLab.laboratorio')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionLab.maquina')),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservación',
                'verbose_name_plural': 'Reservaciones',
            },
        ),
    ]
