# Generated by Django 3.2.9 on 2021-12-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservacion',
            options={'ordering': ['id_reservacion'], 'verbose_name': 'Reservación', 'verbose_name_plural': 'Reservaciones'},
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='id_reservacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
