# Generated by Django 3.1.3 on 2020-12-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservacion',
            options={'ordering': ['id']},
        ),
    ]
