# Generated by Django 3.1.3 on 2020-12-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0002_auto_20201204_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha de la reservación'),
        ),
    ]
