# Generated by Django 3.2.9 on 2021-12-28 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0002_auto_20211225_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservacion',
            options={'ordering': ['fecha'], 'verbose_name': 'Reservación', 'verbose_name_plural': 'Reservaciones'},
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='id_reservacion',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
