# Generated by Django 3.1.3 on 2030-12-11 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0003_auto_20201210_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='solapin',
        ),
    ]
