# Generated by Django 3.2.9 on 2021-12-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0006_auto_20211214_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservacion',
            old_name='local',
            new_name='laboratorio',
        ),
    ]
